---
- name: "Set demo environment settings"
  hosts: master
  gather_facts: no  
  tasks:
  - include_role:
      name: env_config

- name: "Install SSO"
  hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: provision_sso
      when: sso_install
      tags: sso 

- name: "Install APICurio"
  hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: provision_apicurio
      when: apicurio_install
      tags: apicurio

- name: "Install Microcks"
  hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: provision_microcks
      when: microcks_install
      tags: microcks  